server:
  port: 17001

spring:
  application:
    name: investment
  datasource:
    url: jdbc:mysql://192.168.0.103:3306/investment?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: admin
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true

